<?php

declare(strict_types=1);

return [
    /*
     |--------------------------------------------------------------------------
     | Routing configuration
     |--------------------------------------------------------------------------
     |
     | This configuration is used to determine the routing behavior of the
     | Server notifications handler endpoint.
     |
     | You can find more information on documentation.
     | @see https://imdhemy.com/laravel-iap-docs/docs/get-started/routing
     */

    'routing' => [
        'signed' => false,
        'middleware' => ['api'],
        'app-store' => 'liap/notifications/appstore',
        'google-play' => 'liap/notifications/google-play', 
    ],

    /*
     |--------------------------------------------------------------------------
     | Google Play Default Package name
     |--------------------------------------------------------------------------
     |
     | This value is the default package name used when the package name is not
     | provided while verifying the receipts.
     |
     */
    'google_play_package_name' => env('GOOGLE_PLAY_PACKAGE_NAME', 'com.some.thing'),

    /*
     |--------------------------------------------------------------------------
     | Google Application Credentials
     |--------------------------------------------------------------------------
     |
     | This value is the path to the Google Application Credentials file.
     | @see https://imdhemy.com/laravel-iap-docs/docs/credentials/google-play
     |
     */
    'google_application_credentials' => base_path((string)env('GOOGLE_APPLICATION_CREDENTIALS')),

    /*
     |--------------------------------------------------------------------------
     | App Store Password
     |--------------------------------------------------------------------------
     |
     | This value is the app-specific share password generated by the app store.
     | @see https://imdhemy.com/laravel-iap-docs/docs/credentials/app-store
     |
     */
    'appstore_password' => env('APPSTORE_PASSWORD', ''),

    /*
    |--------------------------------------------------------------------------
    | App Store Sandbox Mode
    |--------------------------------------------------------------------------
    |
    | Set to true for development/testing, false for production
    |
    */
    'appstore_sandbox' => env('APPSTORE_SANDBOX', true),

    /*
     |--------------------------------------------------------------------------
     | Event Listeners
     |--------------------------------------------------------------------------
     |
     | This configuration is used to determine the event listeners that will be
     | registered with the application.
     | You can find a list of all available events of the documentation
     |
     | @see https://imdhemy.com/laravel-iap-docs/docs/server-notifications/event-list
     | @see https://imdhemy.com/laravel-iap-docs/docs/get-started/event-listeners
     |
    */
    'eventListeners' => [
        /*
        |--------------------------------------------------------------------------
        | Google Play Events
        |--------------------------------------------------------------------------
        */
        \Imdhemy\Purchases\Events\GooglePlay\SubscriptionRenewed::class => [
            \App\Listeners\HandleGooglePlaySubscriptionRenewed::class,
        ],
        \Imdhemy\Purchases\Events\GooglePlay\SubscriptionCanceled::class => [
            \App\Listeners\HandleGooglePlaySubscriptionCanceled::class,
        ],
        \Imdhemy\Purchases\Events\GooglePlay\SubscriptionRevoked::class => [
            // 处理订阅撤销（例如退款）
        ],
        \Imdhemy\Purchases\Events\GooglePlay\SubscriptionPaused::class => [
            // 处理订阅暂停
        ],
        \Imdhemy\Purchases\Events\GooglePlay\SubscriptionRestarted::class => [
            // 处理订阅重启
        ],

        /*
        |--------------------------------------------------------------------------
        | App Store Events
        |--------------------------------------------------------------------------
        */
        \Imdhemy\Purchases\Events\AppStore\DidRenew::class => [
            \App\Listeners\HandleAppStoreSubscriptionRenewed::class,
        ],
        \Imdhemy\Purchases\Events\AppStore\Cancel::class => [
            \App\Listeners\HandleAppStoreSubscriptionCanceled::class,
        ],
        \Imdhemy\Purchases\Events\AppStore\Refund::class => [
            \App\Listeners\HandleAppStoreRefund::class,
        ],
        \Imdhemy\Purchases\Events\AppStore\DidFailToRenew::class => [
            // 处理续费失败
        ],
        \Imdhemy\Purchases\Events\AppStore\DidRecover::class => [
            // 处理续费恢复
        ],
    ],

    /*
     | --------------------------------------------------------------------------
     | App store JWT configuration
     | --------------------------------------------------------------------------
     |
     | The following configuration is used to generate the JWT token used to
     | authenticate with the App Store server.
     */
    // Your private key ID from App Store Connect (Ex: 2X9R4HXF34)
    'appstore_private_key_id' => env('APPSTORE_PRIVATE_KEY_ID'),
    // The path to your private key file (Ex: /path/to/SuperSecretKey_ABC123.p8)
    'appstore_private_key' => env('APPSTORE_PRIVATE_KEY'),
    // Your issuer ID from the Keys page in App Store Connect (Ex: "57246542-96fe-1a63-e053-0824d011072a")
    'appstore_issuer_id' => env('APPSTORE_ISSUER_ID'),
    // Your app’s bundle ID (Ex: “com.example.testbundleid2021”)
    'appstore_bundle_id' => env('APPSTORE_BUNDLE_ID'),
];
